name: Delete preview from OVH Object Storage

on:
  workflow_run:
    workflows: ["Ask preview removal for a given PR"]
    types:
      - completed

jobs:
  remove:
    name: Delete preview from OVHcloud Object Storage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: PR
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Get PR number
        id: pr_number
        run: echo "pr_number=$(cat PR_NUMBER)" >> $GITHUB_OUTPUT

      - name: Check-out the repo
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/actions/

      - name: Delete preview
        uses: ./.github/actions/delete-preview
        with:
          pull_request_id: ${{ steps.pr_number.outputs.pr_number }}
          os_tenant_id: ${{ secrets.PR_OS_TENANT_ID }}
          os_tenant_name: ${{ secrets.PR_OS_TENANT_NAME }}
          os_username: ${{ secrets.PR_OS_USERNAME }}
          os_password: ${{ secrets.PR_OS_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            _Pull request was merged, preview was removed._
